include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - dart_code_metrics
  code-style:
    format:
      line-length: 140  # or 150, 180, etc.

  errors:
    missing_return: error
    dead_code: warning
    unused_local_variable: warning
    unused_import: warning
    always_declare_return_types: warning
    invalid_assignment: error

  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "**/*.config.dart"
    - "**/*.gen.dart"
    - "lib/generated_plugin_registrant.dart"
    - build/**
    - .dart_tool/**
    - ios/**
    - android/**
    - bloc_feature/**
    - getx_feature/**

linter:
  rules:
    lines_longer_than_80_chars: false
    # Style
    always_declare_return_types: true
    always_put_required_named_parameters_first: true
    curly_braces_in_flow_control_structures: false
    always_put_control_body_on_new_line: false
    always_specify_types: false
    annotate_overrides: true
    avoid_annotating_with_dynamic: true
    avoid_empty_else: true
    avoid_print: true
    avoid_redundant_argument_values: true
    avoid_returning_null: true
    avoid_types_as_parameter_names: true
    camel_case_types: true
    constant_identifier_names: false
    directives_ordering: true
    file_names: true
    flutter_style_todos: true
    library_prefixes: true
    non_constant_identifier_names: false
    omit_local_variable_types: false
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    prefer_single_quotes: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    type_annotate_public_apis: true
    unnecessary_brace_in_string_interps: true
    unnecessary_lambdas: true
    unnecessary_null_checks: true
    use_super_parameters: true
    use_build_context_synchronously: false

